In [2]:
import numpy as np

In [3]:
x = np.array([1, 4, 5, 3, 2, 3])
mu = np.array([0.1, 0.2, 0.4, 0.3, 0.1, 0.5])

In [7]:
nx = np.sort(np.unique(x))
nx

array([1, 2, 3, 4, 5])

In [47]:
np.max(np.repeat(mu[np.newaxis,:], len(nx), axis=0)*(x==nx[:,np.newaxis]), axis=1)

array([0.1, 0.1, 0.5, 0.2, 0.4])

In [50]:
import torch

In [52]:
x = torch.tensor([1, 4, 5, 3, 2, 3])
mu = torch.tensor([0.1, 0.2, 0.4, 0.3, 0.1, 0.5])

In [85]:
nx, _ = torch.sort(torch.unique(x))
nx

tensor([1, 2, 3, 4, 5])

In [81]:
nmu, _ = torch.max(mu.view(1,-1).repeat(nx.size(,1)*(x == nx.view(-1,1)), axis = 1)

In [83]:
nmu

tensor([0.1000, 0.1000, 0.5000, 0.2000, 0.4000])